// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (Product) IsEntity() {}

type Review struct {
	Body     string   `json:"body"`
	Reviewer *User    `json:"reviewer"`
	Product  *Product `json:"product"`
}

type User struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (User) IsEntity() {}
